#!/usr/bin/env node
var fs = require('fs');
var async = require('async');
var crypto = require('crypto')
var prompt = require('prompt');

var common = require('../common.js');

var schema = {
	properties: {
		mnemonic: {description: '12 word mnemonic created with the wallet', pattern: /^([\w]+\s?){12}$/, required: true},
	}
};

var walletFile;
var program = common.program()
	.arguments('<wallet-file>')
	.action(function (_walletFile) {
		walletFile = _walletFile;
	})
	.parse(process.argv);

if (!walletFile) program.help();

async.waterfall([
	getClientDoPrompt,
	recoverWallet,
	common.encryptWallet(walletFile)
], function (err) {
	if (err) console.log('[error] %s', err);
});

function getClientDoPrompt(next) {
	prompt.start();
	async.series({
		client: async.apply(common.getClient, walletFile, program.host, program.verbose),
		prompt: async.apply(prompt.get, schema)
	}, function (err, results) {
		if (err) return next(err);
		return next(null, results.prompt, results.client);
	});
}

function recoverWallet(p, client, next) {
	client.seedFromMnemonic(p.mnemonic, client.credentials);

	return next(null, client);
}