#!/usr/bin/env node
var fs = require('fs');
var path = require('path');
var async = require('async');

var common = require('../common');

var walletFile, outputFile;
var program = common.program()
	.arguments('<wallet-file> <output-file>')
	.action(function (_walletFile, _outputFile) {
		walletFile = _walletFile;
		outputFile = _outputFile;
	});

program.parse(process.argv);
if (!walletFile || !outputFile) program.help();

async.waterfall([
	async.apply(common.getClient, walletFile, program.host, program.verbose),
	exportNoSign,
	fs.writeFile
], function (err) {
	if (err) console.error('[error] %s', err);
});

function exportNoSign(client, next) {
	return next(null, outputFile, client.export({noSign: true}));
}